-- find total customers by countries
SELECT 
country,
COUNT(customer_key) AS total_cust_country
FROM gold.dim_customers
GROUP BY country
ORDER BY total_cust_country DESC

-- find total products by category
SELECT
gender,
COUNT(customer_key) AS total_cust_gender
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_cust_gender DESC

-- find total products by category
SELECT 
category,
COUNT(product_key) AS total_prds_cat
FROM gold.dim_products
GROUP BY category
ORDER BY total_prds_cat DESC

-- what is the avg cost in each category
SELECT 
category,
AVG(cost) AS avg_cost_cat
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost_cat DESC

-- what is the total revenue generated for the each category
SELECT 
p.category,
SUM(sales_amount) AS total_rev_cat
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_rev_cat DESC

-- find total revenue generated by each customer
SELECT 
c.customer_key,
c.first_name,
SUM(f.sales_amount) AS total_rev_cust
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key,c.first_name
ORDER BY total_rev_cust DESC

-- what is the distribution of sold items across countries
SELECT
c.country,
COUNT(f.quantity) AS item_cnt_country
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key = c.customer_key
GROUP BY country
ORDER BY item_cnt_country DESC
